[package]
name = "pad-frames"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "*"
walkdir = "2"
regex = "1"
once_cell = "1"
